### ISSUE TITLE
Heroku Deployment Issue

### ISSUE THREAD

**Issue by hzhu** [itsanna/olive-coders#1]
According to the logs:
```
2016-03-19T17:53:41.851902+00:00 heroku[web.1]: Starting process with command `node server.js`
2016-03-19T17:53:44.317008+00:00 app[web.1]: Listening at http://localhost:5000
2016-03-19T17:54:41.863681+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch

```
[Here's a description of R10](https://devcenter.heroku.com/articles/error-codes#r10-boot-timeout)

To see these logs you will need the [Heroku CLI tool](https://devcenter.heroku.com/articles/heroku-command#installing-the-heroku-cli).

After installing you should be able to type `heroku --version` in terminal and see a valid output.

You'll have to setup your login credentials (user / pass) and then you can access your app's logs by typing this in terminal:

```
heroku logs --tail --app fast-sands-26610
```

**Comment by hzhu** [comment]
Looks like the port is correct, Heroku is using their own port. You we're just logging a static string 
`  console.log('Listening at http://localhost:5000');`

**Comment by hzhu** [comment]
This error isn't specific to your app. I just tried to deploy a simple hello world and got the same issue. Need to investigate more about the deploy process. We must be missing something very simple.

**Comment by hzhu** [comment]
Check out my comment [here](https://github.com/itsanna/olive-coders/commit/61908bc2ed76ff138070fc7211f1c7dfd7be15e6)

**Comment by itsanna** [comment]
I'm able to deploy a simple app [here](http://warm-hamlet-80111.herokuapp.com)

**Comment by itsanna** [comment]
I believe there were two areas that were an issue.

* I received the following error in my Chrome console when I excluded `bundle.js` from git.
`Uncaught SyntaxError: Unexpected token <`

* The way I was listening to the port in `server.js` was giving me a `503 (Service Unavailable)` error.
